server:
  port: 8771

#\u6CE8\u518C\u4E2D\u5FC3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#\u670D\u52A1\u540D\u79F0
spring:
  application:
    name: product-service